### ISSUE TITLE
Zmiany pod Allegro.

### ISSUE THREAD

**Issue by adalbertusgabriel** [sirmacik/css4allegropl#1]
Witaj.

Możesz podać dokładne zmiany jakie wprowadziłeś w kodach Skeleton oraz Normalize aby dostosować je pod Allegro i krótko je opisać? Byłbym wdzięczny,

Doceniam ogólny pomysł ;)

**Comment by sirmacik** [comment]
Cześć

Obawiam się że nie mogę podać Ci dokładnej informacji. Mogę natomiast pokrótce opisać metodę którą to wówczas robiłem:

Pierwszym krokiem było połączenie obu frameworków w formę strawną dla allegro, najpierw normalize, potem skeleton. Z każdym frameworkiem proces wyglądał tak, że najpierw usuwałem kolejne deklaracje elementów nie obsługiwanych przez allegro wg ich dokumentacji a potem usuwałem ich trochę więcej, bo w praktyce dokumentacja była niedokładna. Z resztą podobnie jak dla omawianego rozwiązania.

Wiem, że nie każdemu dobrze grid reaguje ale nie badałem tego nigdy głębiej. Statystycznie problem zgłosiły 2-3 osoby, a znacznie więcej zgłosiło, że im działa świetnie. Może to mieć związek z nieprawidłowo umieszczanymi wewnątrz gridu mediami.

Rozwiązanie powstało na szybko a potem wylądowałem dość daleko od tego tematu i nie będę do niego w określonej przyszłości wracał. Jestem natomiast otwarty na wszelkie usprawnienia jakie ktoś chciałby do tego wprowadzić.

Marcin
